### PR TITLE
Db connector

### PR DESCRIPTION
**Pull request by alex94dmit**
DB-connector is able to perform the connection with InfluxDB on our EC2 instance and perform operations such as: 
- create database
- delete database
- list all databases 
- write dataframe points to database
- query the database
All the code is implemented by @yoshiioko along with testing code, I've done some refactoring.
Don't want to merge it by myself, so asking someone else having this power to do.

### CODE REVIEW

**Comment by THEhEROLocker** [comment]
Can you comment out the second test function. It seems that it is not complete as of now. Correct me if I am wrong.

**Review by danielmargason — APPROVED** [review]
Looks good. I'll merge now.

**Comment by alex94dmit** [comment]
Commented out the second test completely, so it's not causing problems with coverage.

**Comment by THEhEROLocker** [comment]
Thanks. Merging it

**Pull request merged**
