### PR TITLE
Cvs parser

### PR DESCRIPTION
**Pull request by Garrisonix**
This branch is untested.
I added code to read from a csv file into the database. 
there is a notable change to the pandas import that shouldn't change the functionality of the writer.
-from pandas import DataFrame
+import pandas as pd
Though I am not sure, either way it is an easy fix.

### CODE REVIEW

**Comment by alex94dmit** [comment]
On line 50, could you replace DataFrame with pd.DataFrame?

**Comment by alex94dmit** [comment]
And also don't forget to switch it to merging with development instead of master.

**Comment by Garrisonix** [comment]
Everything seems to be working properly. I would say that the next step is to make a test script and to fix the class naming conventions.

**Comment by alex94dmit** [comment]
Waiting for unit tests from Andrew Gonser.

**Comment by THEhEROLocker** [comment]
Fun stuff team. Somebody will get to fix the first merge conflicts. Looks like a simple one.

**Review by THEhEROLocker — APPROVED** [review]

**Pull request merged**
